version: '3.8'
services:
  scraper:
    build: .
    ports:
      - "3500:3500"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev 