version: '3.8'
services:
  scraper:
    build: .
    expose:
      - "3500"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - scraper
    restart: unless-stopped